//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinabits_OM_2017.Web {
    
    
    public partial class DefaultOMVertical {
        
        /// <summary>
        /// UPPopupWindowControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel UPPopupWindowControl;
        
        /// <summary>
        /// PopupWindowControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Controls.XafPopupWindowControl PopupWindowControl;
        
        /// <summary>
        /// LogoLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink LogoLink;
        
        /// <summary>
        /// TIC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Controls.ThemedImageControl TIC;
        
        /// <summary>
        /// UPSAC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel UPSAC;
        
        /// <summary>
        /// SAC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder SAC;
        
        /// <summary>
        /// navigation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel navigation;
        
        /// <summary>
        /// UPNC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel UPNC;
        
        /// <summary>
        /// NC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationActionContainer NC;
        
        /// <summary>
        /// UPVIC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel UPVIC;
        
        /// <summary>
        /// VIC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Controls.ViewImageControl VIC;
        
        /// <summary>
        /// UPVH control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel UPVH;
        
        /// <summary>
        /// VCC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Controls.ViewCaptionControl VCC;
        
        /// <summary>
        /// XafUpdatePanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel XafUpdatePanel1;
        
        /// <summary>
        /// mainMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder mainMenu;
        
        /// <summary>
        /// XafUpdatePanel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel XafUpdatePanel2;
        
        /// <summary>
        /// SearchAC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder SearchAC;
        
        /// <summary>
        /// UPEI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel UPEI;
        
        /// <summary>
        /// ErrorInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.Controls.ErrorInfoControl ErrorInfo;
        
        /// <summary>
        /// UPVSC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel UPVSC;
        
        /// <summary>
        /// VSC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Controls.ViewSiteControl VSC;
        
        /// <summary>
        /// AIC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Controls.AboutInfoControl AIC;
    }
}
