//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinabits_OM_2017.Module.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vinabits_OM_2017.Module.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Dashboard&gt;
        ///  &lt;Title Text=&quot;Bảng tin&quot; /&gt;
        ///  &lt;DataSources&gt;
        ///    &lt;ObjectDataSource ComponentName=&quot;objectDataSource1&quot;&gt;
        ///      &lt;Name&gt;Document&lt;/Name&gt;
        ///      &lt;DataSource Type=&quot;Vinabits_OM_2017.Module.BusinessObjects.Document, Vinabits_OM_2017.Module, Version=1.0.6381.2749, Culture=neutral, PublicKeyToken=null&quot; /&gt;
        ///    &lt;/ObjectDataSource&gt;
        ///    &lt;ObjectDataSource ComponentName=&quot;objectDataSource2&quot;&gt;
        ///      &lt;Name&gt;DocumentEmployees&lt;/Name&gt;
        ///      &lt;DataSource Type=&quot;Vinabits_OM_2017.Module.BusinessObjects.DocumentEmployees [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MainDashBoard {
            get {
                return ResourceManager.GetString("MainDashBoard", resourceCulture);
            }
        }
    }
}
